package com.langsun.domain.finance;

import java.io.Serializable;
import java.util.Date;

public class Finance implements Serializable {

    private String financeId;

    private String packingListId;


    private Date inputDate;

    private String inputBy;

    private Integer state;

    private Double invoiceValue;

    private String contractIds;


    private String companyId;

    private String companyName;


    private String createBy;

    private String createDept;

    private Date createTime;

    private String invoiceNo;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column co_finance.FINANCE_ID
     *
     * @return the value of co_finance.FINANCE_ID
     *
     * @mbg.generated
     */
    public String getFinanceId() {
        return financeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column co_finance.FINANCE_ID
     *
     * @param financeId the value for co_finance.FINANCE_ID
     *
     * @mbg.generated
     */
    public void setFinanceId(String financeId) {
        this.financeId = financeId == null ? null : financeId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column co_finance.PACKING_LIST_ID
     *
     * @return the value of co_finance.PACKING_LIST_ID
     *
     * @mbg.generated
     */
    public String getPackingListId() {
        return packingListId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column co_finance.PACKING_LIST_ID
     *
     * @param packingListId the value for co_finance.PACKING_LIST_ID
     *
     * @mbg.generated
     */
    public void setPackingListId(String packingListId) {
        this.packingListId = packingListId == null ? null : packingListId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column co_finance.INPUT_DATE
     *
     * @return the value of co_finance.INPUT_DATE
     *
     * @mbg.generated
     */
    public Date getInputDate() {
        return inputDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column co_finance.INPUT_DATE
     *
     * @param inputDate the value for co_finance.INPUT_DATE
     *
     * @mbg.generated
     */
    public void setInputDate(Date inputDate) {
        this.inputDate = inputDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column co_finance.INPUT_BY
     *
     * @return the value of co_finance.INPUT_BY
     *
     * @mbg.generated
     */
    public String getInputBy() {
        return inputBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column co_finance.INPUT_BY
     *
     * @param inputBy the value for co_finance.INPUT_BY
     *
     * @mbg.generated
     */
    public void setInputBy(String inputBy) {
        this.inputBy = inputBy == null ? null : inputBy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column co_finance.STATE
     *
     * @return the value of co_finance.STATE
     *
     * @mbg.generated
     */
    public Integer getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column co_finance.STATE
     *
     * @param state the value for co_finance.STATE
     *
     * @mbg.generated
     */
    public void setState(Integer state) {
        this.state = state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column co_finance.invoice_value
     *
     * @return the value of co_finance.invoice_value
     *
     * @mbg.generated
     */
    public Double getInvoiceValue() {
        return invoiceValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column co_finance.invoice_value
     *
     * @param invoiceValue the value for co_finance.invoice_value
     *
     * @mbg.generated
     */
    public void setInvoiceValue(Double invoiceValue) {
        this.invoiceValue = invoiceValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column co_finance.contract_ids
     *
     * @return the value of co_finance.contract_ids
     *
     * @mbg.generated
     */
    public String getContractIds() {
        return contractIds;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column co_finance.contract_ids
     *
     * @param contractIds the value for co_finance.contract_ids
     *
     * @mbg.generated
     */
    public void setContractIds(String contractIds) {
        this.contractIds = contractIds == null ? null : contractIds.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column co_finance.company_id
     *
     * @return the value of co_finance.company_id
     *
     * @mbg.generated
     */
    public String getCompanyId() {
        return companyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column co_finance.company_id
     *
     * @param companyId the value for co_finance.company_id
     *
     * @mbg.generated
     */
    public void setCompanyId(String companyId) {
        this.companyId = companyId == null ? null : companyId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column co_finance.company_name
     *
     * @return the value of co_finance.company_name
     *
     * @mbg.generated
     */
    public String getCompanyName() {
        return companyName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column co_finance.company_name
     *
     * @param companyName the value for co_finance.company_name
     *
     * @mbg.generated
     */
    public void setCompanyName(String companyName) {
        this.companyName = companyName == null ? null : companyName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column co_finance.CREATE_BY
     *
     * @return the value of co_finance.CREATE_BY
     *
     * @mbg.generated
     */
    public String getCreateBy() {
        return createBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column co_finance.CREATE_BY
     *
     * @param createBy the value for co_finance.CREATE_BY
     *
     * @mbg.generated
     */
    public void setCreateBy(String createBy) {
        this.createBy = createBy == null ? null : createBy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column co_finance.CREATE_DEPT
     *
     * @return the value of co_finance.CREATE_DEPT
     *
     * @mbg.generated
     */
    public String getCreateDept() {
        return createDept;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column co_finance.CREATE_DEPT
     *
     * @param createDept the value for co_finance.CREATE_DEPT
     *
     * @mbg.generated
     */
    public void setCreateDept(String createDept) {
        this.createDept = createDept == null ? null : createDept.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column co_finance.CREATE_TIME
     *
     * @return the value of co_finance.CREATE_TIME
     *
     * @mbg.generated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column co_finance.CREATE_TIME
     *
     * @param createTime the value for co_finance.CREATE_TIME
     *
     * @mbg.generated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column co_finance.invoice_no
     *
     * @return the value of co_finance.invoice_no
     *
     * @mbg.generated
     */
    public String getInvoiceNo() {
        return invoiceNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column co_finance.invoice_no
     *
     * @param invoiceNo the value for co_finance.invoice_no
     *
     * @mbg.generated
     */
    public void setInvoiceNo(String invoiceNo) {
        this.invoiceNo = invoiceNo == null ? null : invoiceNo.trim();
    }
}