package com.langsun.domain.packing;

import java.io.Serializable;
import java.util.Date;

public class HomePackingList implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column co_home_packing_list.id
     *
     * @mbg.generated
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column co_home_packing_list.seller
     *
     * @mbg.generated
     */
    private String seller;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column co_home_packing_list.buyer
     *
     * @mbg.generated
     */
    private String buyer;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column co_home_packing_list.mark
     *
     * @mbg.generated
     */
    private String mark;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column co_home_packing_list.descriptions
     *
     * @mbg.generated
     */
    private String descriptions;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column co_home_packing_list.create_by
     *
     * @mbg.generated
     */
    private String createBy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column co_home_packing_list.create_dept
     *
     * @mbg.generated
     */
    private String createDept;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column co_home_packing_list.create_time
     *
     * @mbg.generated
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column co_home_packing_list.export_ids
     *
     * @mbg.generated
     */
    private String exportIds;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column co_home_packing_list.company_id
     *
     * @mbg.generated
     */
    private String companyId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column co_home_packing_list.company_name
     *
     * @mbg.generated
     */
    private String companyName;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column co_home_packing_list.id
     *
     * @return the value of co_home_packing_list.id
     *
     * @mbg.generated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column co_home_packing_list.id
     *
     * @param id the value for co_home_packing_list.id
     *
     * @mbg.generated
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column co_home_packing_list.seller
     *
     * @return the value of co_home_packing_list.seller
     *
     * @mbg.generated
     */
    public String getSeller() {
        return seller;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column co_home_packing_list.seller
     *
     * @param seller the value for co_home_packing_list.seller
     *
     * @mbg.generated
     */
    public void setSeller(String seller) {
        this.seller = seller == null ? null : seller.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column co_home_packing_list.buyer
     *
     * @return the value of co_home_packing_list.buyer
     *
     * @mbg.generated
     */
    public String getBuyer() {
        return buyer;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column co_home_packing_list.buyer
     *
     * @param buyer the value for co_home_packing_list.buyer
     *
     * @mbg.generated
     */
    public void setBuyer(String buyer) {
        this.buyer = buyer == null ? null : buyer.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column co_home_packing_list.mark
     *
     * @return the value of co_home_packing_list.mark
     *
     * @mbg.generated
     */
    public String getMark() {
        return mark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column co_home_packing_list.mark
     *
     * @param mark the value for co_home_packing_list.mark
     *
     * @mbg.generated
     */
    public void setMark(String mark) {
        this.mark = mark == null ? null : mark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column co_home_packing_list.descriptions
     *
     * @return the value of co_home_packing_list.descriptions
     *
     * @mbg.generated
     */
    public String getDescriptions() {
        return descriptions;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column co_home_packing_list.descriptions
     *
     * @param descriptions the value for co_home_packing_list.descriptions
     *
     * @mbg.generated
     */
    public void setDescriptions(String descriptions) {
        this.descriptions = descriptions == null ? null : descriptions.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column co_home_packing_list.create_by
     *
     * @return the value of co_home_packing_list.create_by
     *
     * @mbg.generated
     */
    public String getCreateBy() {
        return createBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column co_home_packing_list.create_by
     *
     * @param createBy the value for co_home_packing_list.create_by
     *
     * @mbg.generated
     */
    public void setCreateBy(String createBy) {
        this.createBy = createBy == null ? null : createBy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column co_home_packing_list.create_dept
     *
     * @return the value of co_home_packing_list.create_dept
     *
     * @mbg.generated
     */
    public String getCreateDept() {
        return createDept;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column co_home_packing_list.create_dept
     *
     * @param createDept the value for co_home_packing_list.create_dept
     *
     * @mbg.generated
     */
    public void setCreateDept(String createDept) {
        this.createDept = createDept == null ? null : createDept.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column co_home_packing_list.create_time
     *
     * @return the value of co_home_packing_list.create_time
     *
     * @mbg.generated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column co_home_packing_list.create_time
     *
     * @param createTime the value for co_home_packing_list.create_time
     *
     * @mbg.generated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column co_home_packing_list.export_ids
     *
     * @return the value of co_home_packing_list.export_ids
     *
     * @mbg.generated
     */
    public String getExportIds() {
        return exportIds;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column co_home_packing_list.export_ids
     *
     * @param exportIds the value for co_home_packing_list.export_ids
     *
     * @mbg.generated
     */
    public void setExportIds(String exportIds) {
        this.exportIds = exportIds == null ? null : exportIds.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column co_home_packing_list.company_id
     *
     * @return the value of co_home_packing_list.company_id
     *
     * @mbg.generated
     */
    public String getCompanyId() {
        return companyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column co_home_packing_list.company_id
     *
     * @param companyId the value for co_home_packing_list.company_id
     *
     * @mbg.generated
     */
    public void setCompanyId(String companyId) {
        this.companyId = companyId == null ? null : companyId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column co_home_packing_list.company_name
     *
     * @return the value of co_home_packing_list.company_name
     *
     * @mbg.generated
     */
    public String getCompanyName() {
        return companyName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column co_home_packing_list.company_name
     *
     * @param companyName the value for co_home_packing_list.company_name
     *
     * @mbg.generated
     */
    public void setCompanyName(String companyName) {
        this.companyName = companyName == null ? null : companyName.trim();
    }
}