package com.langsun.dao.system;


import com.langsun.domain.system.User;

import java.util.List;


public interface UserDao {

	//根据企业id查询全部
	List<User> findAll(String companyId);

	//根据id查询
    User findById(String userId);

	//根据id删除
	int delete(String userId);

	//保存
	int save(User user);

	//更新
	int update(User user);

	void deleteUserRole(String userId);

	void saveUserRoleId(String userId, String splitRoleId);

    User findByEmail(String email);

	int insertSelective(User record);

	/**
	 * This method was generated by MyBatis Generator.
	 * This method corresponds to the database table pe_user
	 *
	 * @mbg.generated
	 */
	int updateByPrimaryKeySelective(User record);

	/**
	 * This method was generated by MyBatis Generator.
	 * This method corresponds to the database table pe_user
	 *
	 * @mbg.generated
	 */

}